CREATE TABLE IF NOT EXISTS `#__loginguard_attempts` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL DEFAULT 0,
  `name` varchar(255) NOT NULL DEFAULT '',
  `username` varchar(255) NULL DEFAULT NULL,
  `email` varchar(255) NOT NULL DEFAULT '',
  `ip_address` varchar(255) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT 'FAILED_LOGIN',
  `browser` varchar(100) NOT NULL DEFAULT '',
  `operating_system` varchar(100) NOT NULL DEFAULT '',
  `country` varchar(100) NOT NULL DEFAULT '',
  `country_code` varchar(10) NOT NULL DEFAULT '',
  `region` varchar(100) NOT NULL DEFAULT '',
  `city` varchar(100) NOT NULL DEFAULT '',
  `isp` varchar(255) NOT NULL DEFAULT '',
  `asn` varchar(50) NOT NULL DEFAULT '',
  `where_at` varchar(50) NOT NULL DEFAULT 'frontend',
  `user_agent` text NOT NULL,
  `attempt_type` varchar(50) NOT NULL DEFAULT 'login',
  `client` varchar(50) NOT NULL DEFAULT 'frontend',
  `reason` text NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_loginguard_user_id` (`user_id`),
  KEY `idx_loginguard_status` (`status`),
  KEY `idx_loginguard_created` (`created`),
  KEY `idx_loginguard_where_at` (`where_at`),
  KEY `idx_loginguard_client` (`client`),
  KEY `idx_loginguard_username` (`username`),
  KEY `idx_loginguard_attempt_type` (`attempt_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__loginguard_blocked_ips` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(255) NOT NULL DEFAULT '',
  `scope` varchar(20) NOT NULL DEFAULT 'all',
  `block_type` varchar(20) NOT NULL DEFAULT 'temporary',
  `reason` varchar(50) NOT NULL DEFAULT 'threshold_exceeded',
  `failure_count` int NOT NULL DEFAULT 0,
  `blocked_until` datetime NULL DEFAULT NULL,
  `created` datetime NOT NULL,
  `created_by` int NOT NULL DEFAULT 0,
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_loginguard_blocked_ip` (`ip_address`),
  KEY `idx_loginguard_blocked_scope` (`scope`),
  KEY `idx_loginguard_blocked_until` (`blocked_until`),
  KEY `idx_loginguard_blocked_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__loginguard_cleanup_runs` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `started_at` datetime NOT NULL,
  `finished_at` datetime NOT NULL,
  `attempts_deleted` int unsigned NOT NULL DEFAULT 0,
  `expired_blocks_deleted` int unsigned NOT NULL DEFAULT 0,
  `disabled_blocks_deleted` int unsigned NOT NULL DEFAULT 0,
  `total_deleted` int unsigned NOT NULL DEFAULT 0,
  `batches` int unsigned NOT NULL DEFAULT 0,
  `batch_size` int unsigned NOT NULL DEFAULT 0,
  `login_retention_days` int unsigned NOT NULL DEFAULT 0,
  `blocked_ip_retention_days` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_loginguard_cleanup_finished_at` (`finished_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
