CREATE TABLE IF NOT EXISTS `#__loginguard_attempts` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `user_id` int NOT NULL DEFAULT 0,
  `name` varchar(255) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL,
  `ip_address` varchar(255) NOT NULL,
  `user_agent` text NOT NULL,
  `country` varchar(100) NOT NULL DEFAULT '',
  `browser` varchar(100) NOT NULL DEFAULT '',
  `operating_system` varchar(100) NOT NULL DEFAULT '',
  `client` varchar(50) NOT NULL,
  `reason` text NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_loginguard_status` (`status`),
  KEY `idx_loginguard_created` (`created`),
  KEY `idx_loginguard_client` (`client`),
  KEY `idx_loginguard_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
