CREATE TABLE IF NOT EXISTS `#__loginguard_attempts` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL DEFAULT 0,
  `name` varchar(255) NOT NULL DEFAULT '',
  `username` varchar(255) NOT NULL DEFAULT '',
  `email` varchar(255) NOT NULL DEFAULT '',
  `ip_address` varchar(255) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT '',
  `browser` varchar(100) NOT NULL DEFAULT '',
  `operating_system` varchar(100) NOT NULL DEFAULT '',
  `country` varchar(100) NOT NULL DEFAULT '',
  `where_at` varchar(50) NOT NULL DEFAULT '',
  `user_agent` text NOT NULL,
  `attempt_type` varchar(50) NOT NULL DEFAULT 'login',
  `client` varchar(50) NOT NULL DEFAULT '',
  `reason` text NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_loginguard_user_id` (`user_id`),
  KEY `idx_loginguard_status` (`status`),
  KEY `idx_loginguard_created` (`created`),
  KEY `idx_loginguard_where_at` (`where_at`),
  KEY `idx_loginguard_client` (`client`),
  KEY `idx_loginguard_username` (`username`),
  KEY `idx_loginguard_attempt_type` (`attempt_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
